package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemStockDO;

public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_item_stock
     *
     * @mbg.generated Fri Dec 27 16:46:27 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_item_stock
     *
     * @mbg.generated Fri Dec 27 16:46:27 CST 2019
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_item_stock
     *
     * @mbg.generated Fri Dec 27 16:46:27 CST 2019
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_item_stock
     *
     * @mbg.generated Fri Dec 27 16:46:27 CST 2019
     */
    ItemStockDO selectByPrimaryKey(Integer id);

    ItemStockDO selectByItemId(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_item_stock
     *
     * @mbg.generated Fri Dec 27 16:46:27 CST 2019
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_item_stock
     *
     * @mbg.generated Fri Dec 27 16:46:27 CST 2019
     */
    int updateByPrimaryKey(ItemStockDO record);
}