package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.OrderDO;

public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_order_info
     *
     * @mbg.generated Mon Jan 06 13:55:27 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_order_info
     *
     * @mbg.generated Mon Jan 06 13:55:27 CST 2020
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_order_info
     *
     * @mbg.generated Mon Jan 06 13:55:27 CST 2020
     */
    int insertSelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_order_info
     *
     * @mbg.generated Mon Jan 06 13:55:27 CST 2020
     */
    OrderDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_order_info
     *
     * @mbg.generated Mon Jan 06 13:55:27 CST 2020
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_order_info
     *
     * @mbg.generated Mon Jan 06 13:55:27 CST 2020
     */
    int updateByPrimaryKey(OrderDO record);
}