package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.SequenceDO;

public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_sequence_info
     *
     * @mbg.generated Mon Jan 06 16:00:15 CST 2020
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_sequence_info
     *
     * @mbg.generated Mon Jan 06 16:00:15 CST 2020
     */
    int insert(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_sequence_info
     *
     * @mbg.generated Mon Jan 06 16:00:15 CST 2020
     */
    int insertSelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_sequence_info
     *
     * @mbg.generated Mon Jan 06 16:00:15 CST 2020
     */
    SequenceDO selectByPrimaryKey(String name);

    SequenceDO getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_sequence_info
     *
     * @mbg.generated Mon Jan 06 16:00:15 CST 2020
     */
    int updateByPrimaryKeySelective(SequenceDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_sequence_info
     *
     * @mbg.generated Mon Jan 06 16:00:15 CST 2020
     */
    int updateByPrimaryKey(SequenceDO record);
}