package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.UserDO;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_user_info
     *
     * @mbg.generated Thu Dec 12 14:42:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_user_info
     *
     * @mbg.generated Thu Dec 12 14:42:58 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_user_info
     *
     * @mbg.generated Thu Dec 12 14:42:58 CST 2019
     */
    int insertSelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_user_info
     *
     * @mbg.generated Thu Dec 12 14:42:58 CST 2019
     */
    UserDO selectByPrimaryKey(Integer id);

    UserDO selectByTelephone(String telephone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_user_info
     *
     * @mbg.generated Thu Dec 12 14:42:58 CST 2019
     */
    int updateByPrimaryKeySelective(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_user_info
     *
     * @mbg.generated Thu Dec 12 14:42:58 CST 2019
     */
    int updateByPrimaryKey(UserDO record);
}